# Generated by Django 5.1.1 on 2025-04-10 22:16

import django.db.models.deletion
import mainApplication.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('title', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('danger', 'Danger')], default='info', max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='systemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowSubmissions', models.BooleanField(default=False)),
                ('allowScientificComitteeDiplomas', models.BooleanField(default=False)),
                ('signature_name', models.CharField(blank=True, max_length=255, null=True)),
                ('logoImageDecisionLetter', models.ImageField(blank=True, null=True, storage=mainApplication.models.OverwriteStorage(), upload_to='images/')),
                ('signatureImageDecisionLetter', models.ImageField(blank=True, null=True, storage=mainApplication.models.OverwriteStorage(), upload_to='images/')),
                ('availabilityDateScientificComitteeDiplomas', models.DateField(blank=True, null=True)),
                ('scientificCommiteeDiplomasTemplate', models.FileField(blank=True, null=True, upload_to='diplomasTemplates/')),
            ],
        ),
        migrations.RemoveField(
            model_name='submissionfile',
            name='description',
        ),
        migrations.AddField(
            model_name='submission',
            name='assigned_reviewers',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='decision_issued',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('minor_changes', 'Accepted with Minor Changes'), ('major_changes', 'Accepted with Major Changes'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='submission',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('minor_changes', 'Accepted with Minor Changes'), ('major_changes', 'Accepted with Major Changes'), ('accepted', 'Accepted')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='review_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submission',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='sent_for_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submission',
            name='under_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publication_type',
            field=models.CharField(choices=[('IEEE', 'IEEE'), ('Springer', 'Springer'), ('Other', 'Other')], max_length=50),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('reject', 'Reject: Content inappropriate to the conference or has little merit'), ('probable_reject', 'Probable Reject: Basic flaws in content or presentation or very poorly written'), ('marginal_reject', 'Marginal Tend to Reject: Not as badly flawed; major effort necessary'), ('marginal_accept', 'Marginal Tend to Accept: Content has merit, but needs improvement'), ('clear_accept', 'Clear Accept: Content, presentation, and writing meet professional norms'), ('must_accept', 'Must Accept: Candidate for outstanding submission')], max_length=20)),
                ('categorization', models.CharField(choices=[('highly_theoretical', 'Highly theoretical'), ('tends_theoretical', 'Tends towards theoretical'), ('balanced', 'Balanced theory and practice'), ('tends_practical', 'Tends toward practical'), ('highly_practical', 'Highly practical')], max_length=20)),
                ('new_information', models.BooleanField(default=False)),
                ('valuable_confirmation', models.BooleanField(default=False)),
                ('clarity_to_understanding', models.BooleanField(default=False)),
                ('new_perspective', models.BooleanField(default=False)),
                ('not_much', models.BooleanField(default=False)),
                ('other_value', models.TextField(blank=True)),
                ('reviewer_familiarity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('best_submission_candidate', models.BooleanField(default=False)),
                ('appropriate_length', models.BooleanField(default=False)),
                ('difference_from_previous', models.CharField(choices=[('different', 'Totally or largely different from other submissions'), ('moderate', 'Moderately different from other submissions'), ('identical', 'Totally or largely identical to other submissions'), ('unsure', "Don't know")], max_length=20)),
                ('author_comments', models.TextField()),
                ('committee_comments', models.TextField()),
                ('email_form', models.BooleanField(default=False)),
                ('review_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_round_number', models.PositiveIntegerField(default=1)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApplication.submission')),
            ],
        ),
        migrations.CreateModel(
            name='reviewersCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, unique=True)),
                ('used', models.BooleanField(default=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewer_codes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
