# Generated by Django 5.1.1 on 2024-10-11 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allEvent',
            field=models.BooleanField(default=False, verbose_name='This event last all the congress? '),
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='Links of online meeting: '),
        ),
        migrations.AddField(
            model_name='event',
            name='requisites',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='Requisites: '),
        ),
        migrations.AddField(
            model_name='registration',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='FullName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (The name you write will be the one under which your certificates will be issued)'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='amount',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='manualPayment',
            field=models.BooleanField(default=False),
        ),
    ]
