# Generated by Django 5.1.1 on 2024-09-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0002_userprofile_delete_customuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paper_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='paper_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
