# Generated by Django 5.1.1 on 2024-10-04 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0002_event_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='links',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='Links of online meeting: '),
        ),
    ]
