# Generated by Django 5.1.1 on 2025-01-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0002_remove_submissionfile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='sent_for_review',
            field=models.BooleanField(default=False),
        ),
    ]
