# Generated by Django 5.1.1 on 2024-10-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0002_event_allevent_event_banner_event_links_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='fileDiplomas',
            field=models.FileField(blank=True, null=True, upload_to='diplomasTemplates/'),
        ),
    ]
