# Generated by Django 5.1.1 on 2024-10-04 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0003_event_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='FullName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
