# Generated by Django 5.1.1 on 2024-09-30 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0003_userprofile_paper_id_userprofile_paper_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='paper_id',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='paper_name',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('author', 'Author'), ('public', 'General Public'), ('student', 'Student'), ('guest', 'Guest'), ('other', 'Other')], max_length=20),
        ),
    ]
