# Generated by Django 5.1.1 on 2025-01-15 03:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0003_submission_sent_for_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='reviewers',
            field=models.ManyToManyField(blank=True, related_name='assigned_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='submission',
            name='under_review',
            field=models.BooleanField(default=False),
        ),
    ]
