# Generated by Django 5.1.1 on 2024-10-05 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0004_userprofile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='requisites',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True, verbose_name='Requisites: '),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='FullName',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Full Name (The name you write will be the one under which your certificates will be issued)'),
        ),
    ]
