# Generated by Django 5.1.1 on 2025-01-17 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0004_submission_reviewers_submission_under_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_withdrawn',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='publication_type',
            field=models.CharField(choices=[('IEEE', 'IEEE'), ('Springer', 'Springer'), ('Other', 'Other')], max_length=50),
        ),
    ]
