# Generated by Django 5.1.1 on 2025-01-18 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0005_submission_is_withdrawn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewersCodes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255)),
                ('used', models.BooleanField(default=False)),
            ],
        ),
    ]
