# Generated by Django 5.1.1 on 2024-10-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0005_event_requisites_alter_userprofile_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='allEvent',
            field=models.BooleanField(default=False),
        ),
    ]
