# Generated by Django 5.1.1 on 2024-09-30 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0006_userprofile_payment_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='payment_observarions',
            field=models.CharField(default=' ', max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user_type',
            field=models.CharField(choices=[('author', 'Author'), ('public', 'General Public'), ('student', 'Student')], max_length=20),
        ),
    ]
