# Generated by Django 5.1.1 on 2024-10-06 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0006_event_allevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='counter',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='allEvent',
            field=models.BooleanField(default=False, verbose_name='This event last all the congress? '),
        ),
    ]
