# Generated by Django 5.1.1 on 2025-01-18 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0006_reviewerscodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewerscodes',
            name='code',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
