# Generated by Django 5.1.1 on 2025-01-19 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0008_reviewerscodes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewerscodes',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
