# Generated by Django 5.1.1 on 2024-09-30 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0008_paymentproof'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
    ]
