# Generated by Django 5.1.1 on 2025-01-19 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0009_reviewerscodes_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='assigned_reviewers',
            field=models.BooleanField(default=False),
        ),
    ]
