# Generated by Django 5.1.1 on 2024-09-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0009_paymentproof_rejected'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproof',
            name='transactionID',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
