# Generated by Django 5.1.1 on 2025-01-20 05:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0010_submission_assigned_reviewers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.CharField(choices=[('reject', 'Reject: Content inappropriate to the conference or has little merit'), ('probable_reject', 'Probable Reject: Basic flaws in content or presentation or very poorly written'), ('marginal_reject', 'Marginal Tend to Reject: Not as badly flawed; major effort necessary'), ('marginal_accept', 'Marginal Tend to Accept: Content has merit, but needs improvement'), ('clear_accept', 'Clear Accept: Content, presentation, and writing meet professional norms'), ('must_accept', 'Must Accept: Candidate for outstanding submission')], max_length=20)),
                ('categorization', models.CharField(choices=[('highly_theoretical', 'Highly theoretical'), ('tends_theoretical', 'Tends towards theoretical'), ('balanced', 'Balanced theory and practice'), ('tends_practical', 'Tends toward practical'), ('highly_practical', 'Highly practical')], max_length=20)),
                ('new_information', models.BooleanField(default=False)),
                ('valuable_confirmation', models.BooleanField(default=False)),
                ('clarity_to_understanding', models.BooleanField(default=False)),
                ('new_perspective', models.BooleanField(default=False)),
                ('not_much', models.BooleanField(default=False)),
                ('other_value', models.TextField(blank=True)),
                ('reviewer_familiarity', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], max_length=10)),
                ('best_submission_candidate', models.BooleanField(choices=[('yes', 'Yes'), ('no', 'No'), ('unsure', 'Unsure')], max_length=10)),
                ('appropriate_length', models.BooleanField(null=True)),
                ('difference_from_previous', models.CharField(choices=[('different', 'Totally or largely different from other submissions'), ('moderate', 'Moderately different from other submissions'), ('identical', 'Totally or largely identical to other submissions'), ('unsure', "Don't know")], max_length=20)),
                ('author_comments', models.TextField()),
                ('committee_comments', models.TextField()),
                ('email_form', models.BooleanField(default=False)),
                ('review_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApplication.submission')),
            ],
        ),
    ]
