# Generated by Django 5.1.1 on 2024-09-30 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0010_paymentproof_transactionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproof',
            name='transactionID',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='transactionID',
            field=models.CharField(default=' ', max_length=255),
        ),
    ]
