# Generated by Django 5.1.1 on 2025-01-20 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0011_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appropriate_length',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='review',
            name='best_submission_candidate',
            field=models.BooleanField(default=False),
        ),
    ]
