# Generated by Django 5.1.1 on 2024-09-30 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0011_remove_paymentproof_transactionid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='transactionID',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
