# Generated by Django 5.1.1 on 2025-01-21 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0012_alter_review_appropriate_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='decision_issued',
            field=models.BooleanField(default=False),
        ),
    ]
