# Generated by Django 5.1.1 on 2025-01-22 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0013_submission_decision_issued'),
    ]

    operations = [
        migrations.CreateModel(
            name='systemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowSubmissions', models.BooleanField(default=False)),
                ('allowScientificComitteeDiplomas', models.BooleanField(default=False)),
            ],
        ),
    ]
