# Generated by Django 5.1.1 on 2025-01-23 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0014_systemsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('rejected', 'Rejected'), ('minor_changes', 'Accepted with Minor Changes'), ('major_changes', 'Accepted with Major Changes'), ('accepted', 'Accepted')], max_length=20, null=True),
        ),
    ]
