# Generated by Django 5.1.1 on 2024-09-30 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0014_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('ieee', 'IEEE Article'), ('springer', 'Springer Article'), ('keynote', 'Keynote'), ('lunch', 'Lunch'), ('workshop', 'Workshop'), ('other', 'Other')], default='other', max_length=50),
        ),
    ]
