# Generated by Django 5.1.1 on 2025-01-23 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0015_submission_final_decision'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='signature_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
