# Generated by Django 5.1.1 on 2024-09-30 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0016_congressdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ponent_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
