# Generated by Django 5.1.1 on 2025-01-23 20:36

import mainApplication.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0016_systemsettings_signature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='logoImageDecisionLetter',
            field=models.ImageField(blank=True, null=True, storage=mainApplication.models.OverwriteStorage(), upload_to='images/'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='signatureImageDecisionLetter',
            field=models.ImageField(blank=True, null=True, storage=mainApplication.models.OverwriteStorage(), upload_to='images/'),
        ),
    ]
