# Generated by Django 5.1.1 on 2025-01-24 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0017_systemsettings_logoimagedecisionletter_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='review_round',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='submissionfile',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='submission',
            name='decision_issued',
            field=models.CharField(choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('minor_changes', 'Accepted with Minor Changes'), ('major_changes', 'Accepted with Major Changes'), ('accepted', 'Accepted')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='submission',
            name='final_decision',
            field=models.CharField(blank=True, choices=[('pending', 'Pending'), ('rejected', 'Rejected'), ('minor_changes', 'Accepted with Minor Changes'), ('major_changes', 'Accepted with Major Changes'), ('accepted', 'Accepted')], max_length=20, null=True),
        ),
    ]
