# Generated by Django 5.1.1 on 2024-09-30 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0017_event_ponent_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='affiliation',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
