# Generated by Django 5.1.1 on 2024-09-30 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0018_event_affiliation'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='moderator',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
