# Generated by Django 5.1.1 on 2025-01-24 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0018_submission_review_round_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='revision_round_number',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
