# Generated by Django 5.1.1 on 2025-01-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0019_review_revision_round_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='availabilityDateScientificComitteeDiplomas',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='scientificCommiteeDiplomasTemplate',
            field=models.FileField(blank=True, null=True, upload_to='diplomasTemplates/'),
        ),
    ]
