# Generated by Django 5.1.1 on 2024-10-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0019_event_moderator'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='current_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
