# Generated by Django 5.1.1 on 2024-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0020_place_current_capacity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='current_capacity',
        ),
        migrations.AddField(
            model_name='registration',
            name='assisted',
            field=models.BooleanField(default=False),
        ),
    ]
