# Generated by Django 5.1.1 on 2024-10-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0021_remove_place_current_capacity_registration_assisted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='permitirRegistro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recibioKIT',
            field=models.BooleanField(default=False),
        ),
    ]
