# Generated by Django 5.1.1 on 2025-01-24 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0021_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='enlace_url',
            new_name='url',
        ),
    ]
