# Generated by Django 5.1.1 on 2024-10-03 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApplication', '0022_userprofile_permitirregistro_userprofile_recibiokit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='payment_observarions',
            field=models.CharField(blank=True, default=' ', max_length=255, null=True),
        ),
    ]
